export const KEY_API =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxc2ZjYXR0bG5mdXZicGlwcGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzE1MjY4MjMsImV4cCI6MTk4NzEwMjgyM30.FTPcP6uquKxWLdeRGFixv3JRJO3v0VhezWDeH0Jnnjg";
export const DATA_URL =
  "https://wqsfcattlnfuvbpippfh.supabase.co/rest/v1/facts";
